#! /bin/sh

### BEGIN INIT INFO
# Provides:          L2tpIPsecVpnControlDaemon
# Required-Start:    $remote_fs $network $syslog
# Required-Stop:     $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Daemon used to start/stop L2TP over IPsec VPN connections by non privileged users
# Description:       Daemon used to start/stop L2TP over IPsec VPN connections by non privileged users
### END INIT INFO

NAME=L2tpIPsecVpnControlDaemon
DESC=L2tpIPsecVpnControlDaemon
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/$NAME

test -x $DAEMON || exit 0

# Include L2tpIPsecVpnControlDaemon defaults if available
if [ -f /etc/default/$NAME ] ; then
	. /etc/default/$NAME
fi

PIDFILE=/var/run/$NAME.pid

# set the environment vaiables needed by the daemon
export HOME=/root
export DISPLAY=":0.0"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	test -d ${L2TP_IPSEC_VPN_CONTROLD_RUN_DIR:-/var/run/$NAME} || mkdir -p ${L2TP_IPSEC_VPN_CONTROLD_RUN_DIR:-/var/run/$NAME}
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --oknodo --stop --quiet --pidfile $PIDFILE --exec $DAEMON
	echo "$NAME."
	;;
  force-reload)
	test -d ${L2TP_IPSEC_VPN_CONTROLD_RUN_DIR:-/var/run/$NAME} || mkdir -p ${XL2TP_IPSEC_VPN_CONTROLD_RUN_DIR:-/var/run/$NAME}
	# check whether $DAEMON is running. If so, restart
	start-stop-daemon --stop --test --quiet --pidfile $PIDFILE --exec $DAEMON && $0 restart || exit 0
	;;
  restart)
	test -d ${L2TP_IPSEC_VPN_CONTROLD_RUN_DIR:-/var/run/$NAME} || mkdir -p ${L2TP_IPSEC_VPN_CONTROLD_RUN_DIR:-/var/run/$NAME}
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --exec $DAEMON
	sleep 1
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
